config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'about', to: 'pages#about', as: :about
  get 'portfolio', to: 'pages#portfolio', as: :portfolio
  get 'contact', to: 'pages#contact', as: :contact

  resources :contact, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/home.rb
class Home < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about
  end

  def portfolio
  end

  def home
  end

  def contact
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quanna testing page</title>
    <meta name="viewport" charset="UTF-8" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="about-page-container">
  <div class="header">
    <div class="logo">
      <h1>
        <span>Quanna</span>
      </h1>
    </div>
    <div class="header-links">
      <%= link_to "My work", portfolio_path, class: 'link-to-portfolio' %>
      <%= link_to "Contact", contact_path, class: 'link-to-contact'  %>
      <%= link_to "Homepage", root_path, class: 'link-to-home'  %>
    </div>
  </div>

  <div class="about-page-main">
    <div class="about-section first">
      <div class="about-section-picture">
        <img class="photo-about" src="<%= asset_path('photo-three.jpg') %>">
      </div>
      <div class="about-section-text">
        <div class="text-box first"> Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque beatae cum repellendus quae, minus sequi consequatur rem dolorem omnis a eligendi aspernatur ad aut fuga voluptates corrupti dolorum provident et?
        </div>
      </div>
    </div>
    <div class="about-section second">
      <div class="about-section-text">
        <div class="text-box second"> Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae sit dicta reiciendis, provident doloribus blanditiis incidunt rerum pariatur laudantium nostrum laborum voluptatibus sint porro autem molestiae eligendi enim ipsam eaque.
        </div>
      </div>
      <div class="about-section-picture">
        <img class="photo-about" src="<%= asset_path('photo-six.jpg') %>">
      </div>
    </div>
    <div class="about-section third">
      <div class="about-section-picture">
        <img class="photo-about" src="<%= asset_path('photo-two.jpg') %>">
      </div>
      <div class="about-section-text">
        <div class="text-box third"> Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae sit dicta reiciendis, provident doloribus blanditiis incidunt rerum pariatur laudantium nostrum laborum voluptatibus sint porro autem molestiae eligendi enim ipsam eaque.
        </div>
      </div>
    </div>
    <div class="about-section fourth">
      <div class="about-section-text">
        <div class="text-box fourth"> Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis, consequuntur? Perferendis, aperiam eum consequuntur, quisquam aliquam, corporis velit vel reiciendis sequi soluta adipisci reprehenderit quod debitis nam odio inventore? Cum!
        </div>
      </div>
      <div class="about-section-picture">
        <img class="photo-about" src="<%= asset_path('photo-five.jpg') %>">
      </div>
    </div>
    <div class="about-section fifth">
      <div class="about-section-picture">
        <img class="photo-about" src="<%= asset_path('photo-four.jpg') %>">
      </div>
      <div class="about-section-text">
        <div class="text-box fifth"> Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae sit dicta reiciendis, provident doloribus blanditiis incidunt rerum pariatur laudantium nostrum laborum voluptatibus sint porro autem molestiae eligendi enim ipsam eaque.
        </div>
      </div>
    </div>
  </div>

  <div class="footer">
    <div class="footer-left">
      <div class='footer-icon'><%= link_to icon('fa-brands', 'imdb fa-2x'), 'https://www.imdb.com/name/nm9973363/?ref_=nv_sr_srsg_1', :target => "_blank" %></div>
      <div class='footer-icon'><%= link_to icon('fa-brands', 'instagram fa-2x'), 'https://www.instagram.com/quanna_l/', :target => "_blank" %></div>
      <div class='footer-icon'><%= link_to icon('fa-brands', 'twitter fa-2x'), 'https://twitter.com/quannaluo?lang=en-GB', :target => "_blank"%></div>
      <div class='footer-icon'><%= link_to icon('fa-regular', 'comments fa-2x'), 'https://www.sueterryvoices.com/artist/quanna-luo-masterson', :target => "_blank"%></div>
    </div>
    <div class="footer-right">
  <%# <%= link_to "Back to the top", about_path, class: 'link-footer'  %>
    </div>
  </div>
</div>

app/views/pages/contact.html.erb
<div class="contact-container">
  <div class="header">
    <div class="logo">
      <h1>
        <span>Quanna</span>
      </h1>
    </div>
    <div class="header-links">
      <%= link_to "About me", about_path, class: 'link-to-about' %>
      <%= link_to "portfolio", portfolio_path, class: 'link-to-portfolio'  %>
      <%= link_to "Homepage", root_path, class: 'link-to-home'  %>
    </div>
  </div>


  <div class="contact-page-container">

    <h2 class='contact-form-title'>Contact me</h2>

    <div class="form-container">
      <div class="contact-form">
        <form class='form' action="mailto:someone@example.com" method="post" enctype="text/plain">
        Name:<br>
        <div class="form-name">
          <input class='form-name-item first' type="text" name="first-name" placeholder='First'><br>
          <input class='form-name-item second' type="text" name="last-name" placeholder='Last'><br>
        </div>
        E-mail:<br>
        <input class='form-email' type="text" name="email" placeholder='example@email.com'><br>
        Message:<br>
        <input class='form-message' class='form-name' type="text" name="message" size="50" placeholder='Your message here ...'>
        <br><br>
        <input class='submit-btn' type="submit" value="Send">
        <input class='reset-btn' type="reset" value="Reset">
        </form>
      </div>
      <div class='picture-form-container'>
        <img class="picture-form" src="<%= asset_path('q3.jpg') %>">
      </div>
    </div>

  </div>



    <div class="footer">
    <div class="footer-left">
      <div class='footer-icon'><%= link_to icon('fa-brands', 'imdb fa-2x'), 'https://www.imdb.com/name/nm9973363/?ref_=nv_sr_srsg_1', :target => "_blank" %></div>
      <div class='footer-icon'><%= link_to icon('fa-brands', 'instagram fa-2x'), 'https://www.instagram.com/quanna_l/', :target => "_blank" %></div>
      <div class='footer-icon'><%= link_to icon('fa-brands', 'twitter fa-2x'), 'https://twitter.com/quannaluo?lang=en-GB', :target => "_blank"%></div>
      <div class='footer-icon'><%= link_to icon('fa-regular', 'comments fa-2x'), 'https://www.sueterryvoices.com/artist/quanna-luo-masterson', :target => "_blank"%></div>
    </div>
    <div class="footer-right">
  <%# <%= link_to "Back to the top", contact_path, class: 'link-footer'  %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="home-page-container">

  <div class="home-main-container  ">


      <div class="title-name">
        <h1>Quanna</h1>
        <h1>Luo</h1>
        <h1>Masterson</h1>
      </div>


  </div>

    <div class="link-buttons">
      <%= link_to "About me", about_path, class: 'link' %>
      <%= link_to "Portfolio", portfolio_path, class: 'link'  %>
      <%= link_to "contact", contact_path, class: 'link' %>
    </div>

</div>

app/views/pages/portfolio.html.erb
<div class="portfolio-container">
  <div class="header">
    <div class="logo">
      <h1>
        <span>Quanna</span>
      </h1>
    </div>
    <div class="header-links">
      <%= link_to "About me", about_path, class: 'link-to-about' %>
      <%= link_to "Contact", contact_path, class: 'link-to-contact'  %>
      <%= link_to "Homepage", root_path, class: 'link-to-home'  %>
    </div>
  </div>
  <div class="portfolio-page-container">
    <%# <div class="photos-container">
      <div class="photo-box">
      </div>
      <div class="photo-box">
      </div>
      <div class="photo-box">
      </div>
    </div> %>
    <div class="video-box" style="padding:56.25% 0 0 0;position:relative;">
      <%# <video class='showreel' src="https://player.vimeo.com/video/759278307?h=d17e02542a" controls></video> %>
      <iframe src="https://player.vimeo.com/video/759278307?h=d17e02542a" style="position:absolute;top:0;width:90%;height:100%;" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe>
      <%# <script src="https://player.vimeo.com/api/player.js"></script> %>
    </div>
    <div class="quote-container-portfolio">
      <h1>
        <span>There</span>
        <span>are</span>
        <span>no</span>
        <span>limits</span>
        <span>to</span>
        <span>what</span>
        <span>you</span>
        <span>can</span>
        <span>accomplish,</span>
        <span>except</span>
        <span>the</span>
        <span>limits</span>
        <span>you</span>
        <span>place</span>
        <span>on</span>
        <span>your</span>
        <span>own</span>
        <span>thinking.</span>
      </h1>
      <h1>
        <span>The</span>
        <span>only</span>
        <span>impossible</span>
        <span>journey</span>
        <span>is</span>
        <span>the</span>
        <span>one</span>
        <span>you</span>
        <span>don't,</span>
        <span>begin.</span>
      </h1>
    </div>
      <div class="audio-box">
        <p class='audio-title'>Mandarin commercial</p>
          <audio class="voice-reel" src="<%= audio_path('mandarin-speaking-commercial.mp3') %>" controls type="audio/mp3"></audio>
        <p class='audio-title'>English Commercial</p>
          <audio class="voice-reel" src="<%= audio_path('qm-english.mp3') %>" controls type="audio/mp3"></audio>
        <p class='audio-title'>HSBC</p>
          <audio class="voice-reel" src="<%= audio_path('english-hsbc.mp3') %>" controls type="audio/mp3"></audio>
      </div>
    <div class="photos-container">
      <div class="photo-box">
      </div>
      <div class="photo-box">
      </div>
      <div class="photo-box">
      </div>
      <div class="photo-box">
      </div>
      <div class="photo-box">
      </div>
      <div class="photo-box">
      </div>
    </div>


  </div>


  <div class="footer">
    <div class="footer-left">
      <div class='footer-icon'><%= link_to icon('fa-brands', 'imdb fa-2x'), 'https://www.imdb.com/name/nm9973363/?ref_=nv_sr_srsg_1', :target => "_blank" %></div>
      <div class='footer-icon'><%= link_to icon('fa-brands', 'instagram fa-2x'), 'https://www.instagram.com/quanna_l/', :target => "_blank" %></div>
      <div class='footer-icon'><%= link_to icon('fa-brands', 'twitter fa-2x'), 'https://twitter.com/quannaluo?lang=en-GB', :target => "_blank"%></div>
      <div class='footer-icon'><%= link_to icon('fa-regular', 'comments fa-2x'), 'https://www.sueterryvoices.com/artist/quanna-luo-masterson', :target => "_blank"%></div>
    </div>
    <div class="footer-right">
  <%# <%= link_to "Back to the top", portfolio_path, class: 'link-footer'  %>
    </div>
  </div>
</div>